### ISSUE TITLE
Block API Version 3 does not inject CSS modifications

### ISSUE THREAD

**Issue by dkjensen** [10up/10up-toolkit#374] opened 2024-03-03 13:04 UTC
### Describe the bug

When using `"apiVersion": 3` within a **block.json**, associated styles and editor styles do not inject CSS updates.

### Steps to Reproduce

1. Clone `10up-theme`
2. Modify `includes/blocks/example-block/block.json`, change to `apiVersion` to **3**
3. Add a `style.css` file to the block, register the style within `block.json`, and import it within `index.js`.
4. Run `npm run watch`, and modify the CSS to test.

### Screenshots, screen recording, code snippet

https://github.com/10up/10up-toolkit/assets/1517909/b12174f8-9fea-4791-b221-bb78d6691335

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment] 2024-03-13 08:23
@dkjensen Thanks for your report. This is a duplicate of #168 

Currently the CSS entry points that get defined via block.json don't support hot module reloading

**Closed as completed by fabiankaegy** 2024-03-13 08:23 UTC
