### ISSUE TITLE
Toolkit creates invalid CSS when using double parentheses with `calc()`

### ISSUE THREAD

**Issue by derweili** [10up/10up-toolkit#308] opened 2023-07-12 14:26 UTC
### Describe the bug

When using `calc` with double parentheses, toolkit produces invalid css output

Example input:
```css
margin-left: calc((var(--inset-content-margin) * -1));
``` 

Example output
```css
margin-left: (var(--inset-content-margin) * -1);
```

I know, having double parentheses is uncommon and unnecessary, but it's valid CSS according to [W3C CSS Validator](https://jigsaw.w3.org/css-validator/validator) so I would expect toolkit to produce valid output.

This did not happen in toolkit version `^1.0.13`.

### Steps to Reproduce

1. Apply following styles to an element: 
```css
--inset-content-margin: 1rem;
margin-left: (var(--inset-content-margin) * -1);
```
2. Run build process. You will see the invalid CSS mentioned above.

### Screenshots, screen recording, code snippet

<img width="387" alt="Bildschirmfoto 2023-07-12 um 15 13 50" src="https://github.com/10up/10up-toolkit/assets/6911678/8f2a8bfc-f641-40ea-b304-e420629f5c6f">

### Environment information

- Toolkit Version: 4.3.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Antonio-Laguna** [comment] 2023-07-12 14:31
@derweili could you provide more info regarding the steps to reproduce? It kind of goes in a different way to the first examples you pasted so I want to be sure I'm looking at the right thing.

**Comment by derweili** [comment] 2023-07-12 14:56
@Antonio-Laguna I just did some tests. So the issue only occurs with double parantheses combined with a custom property:

This works:
```css
/** Input: **/
max-width: calc(100vw - 500px));

/** Output: **/
max-width: calc(100vw - 500px));
```

This does not work:
```css
/** Input: **/
max-width: calc((var(--my-width) - 500px));

/** Output: **/
max-width: (var(--my-width) - 500px)
```

What other information do you need?

**Comment by Antonio-Laguna** [comment] 2023-07-12 14:58
I'm unsure how a calc would be removed in this instance. I'll dig deeper :)

**Comment by Antonio-Laguna** [comment] 2023-07-26 10:20
@derweili This is caused by CSSNANO and it's this issue specifically https://github.com/postcss/postcss-calc/issues/77

I'd suggest my suggestion is not to add several parenthesis for the time being or disabling calc from CSSNANO but given you can still benefit from some of the calc benefits I'd say the former is preferred

**Comment by nicholasio** [comment] 2023-08-02 12:50
It sounds like this isn't something we can actually fix in toolkit so I'm closing this issue but if there's anything we need to do in toolkit regarding this issue feel free to reope.

**Closed as completed by nicholasio** 2023-08-02 12:50 UTC
Labels: [Type] Bug
