### ISSUE TITLE
Pseduo elements inside a mixin does not work properly in block styles

### ISSUE THREAD

**Issue by saltnpixels** [10up/10up-toolkit#88] opened 2021-07-15 14:44 UTC
**Describe the bug**

Any styles for the back end goes through a postCSS plugin, **postcss-editor-styles**.
This wraps all selectors with `.editor-styles-wrapper`.

For some reason if a mixin with a pseudo element is used inside any back end styles, the pseudo elements do not come through and compile improperly with a double wrapping of `.editor-styles-wrapper.`

**Steps to Reproduce**

1. Create a mixin with a pseudo element like so:
```CSS
@define-mixin button-primary {
   background: red;
   color: white;
    
   &::after {
     content: "10up";
   }
}
```

2. Add the mixin to an element inside the blocks folder or any file being imported into the editor-style.css file.
```CSS
.wp-block-button {
   & .wp-block-button__link {
		@mixin button-primary;
	}
}
```

3. Compile with `npm run build` the postCSS and the mixin gets messed up. The output for the pseudo style looks like this:
```CSS
.editor-styles-wrapper .editor-styles-wrapper .wp-block-button .wp-block-button__link:after{
   background: red;
   color: white;
    
   &::after {
     content: "10up";
   }
}
```

As you can see, it gets double wrapped, and therefore never works on the back end. 

**Expected behavior**

Don't double wrap the mixin pseudo selector

**Comment by nicholasio** [comment] 2021-09-15 17:44
the postcss editor style package doesn't seem to be actively maintained anymore. Not sure if there are better alternatives but we could also fork it (the plugin is not very complicated) and fxi this ouselves.

**Comment by nicholasio** [comment] 2021-11-22 17:34
Confirmed this bug in this test case: https://github.com/10up/10up-toolkit/pull/116

I don't really see another way to fix this that doesn't involve forking the postcss-editor-style plugin.

I'm not sure if there are any other alternatives plugins that would do a similar job. cc @Antonio-Laguna @joesnellpdx @fabiankaegy

**Comment by Antonio-Laguna** [comment] 2021-11-22 17:45
@nicholasio I've done a quick search and couldn't find a plugin (though I can swear there was something more generic to wrap with *any* class) 

`postcss-editor-style` is not compatible with 8.0.0 and it seems like it's abandoned (as you pointed). This feels like a good plugin we could do and I could potentially put some time into this throughout the week.

cc @joesnellpdx @fabiankaegy

**Comment by nicholasio** [comment] 2021-11-22 18:06
@Antonio-Laguna That'd be awesome! I think we can start by just moving the postcss plugin into 10up-toolkit itself and load it through our postcss config.

**Comment by fabiankaegy** [comment] 2021-11-22 18:15
This may be a surprise but I am not sure we actually need the functionality of the plugin any longer. 

Coming out of this discussion here: https://github.com/WordPress/gutenberg/issues/33212#issuecomment-879205480

> `add_editor_style` is the official way to add styles to the editor. This was even already the case in the classic editor.

What `add_editor_style` does is inline the stylesheet in the editor and automatically scope the styles to the `.editor-styles-wrapper` class. 

If we switch to this approach for our theme stylesheets we would no longer need the post css plugin as WordPress Core takes care of it by itself. 

If we have cases where we need to style things outside of the post content that shouldn't happen in the regular stylesheet anyways and right now we are fighting the postcss plugin to allow styles to break out of the wrapping class. This differentiation may actually give us some more clarity in how that is working. 

For reference here is a commit of an internal project where I showed switching the approach: https://gitlab.10up.com/hillel/hillel/-/commit/616a6f4ca775b03c9a2a3da6f49927449747845e

**Comment by nicholasio** [comment] 2021-11-22 18:59
That's a great point.

I don't remember if there was a specific reason we went with this postcss plugin.

**Comment by fabiankaegy** [comment] 2021-11-22 19:07
To be clear. The current wp-scaffold does not work this way and does not leverage the `add_editor_style` so I think that should be changed amongst this.

**Comment by nicholasio** [comment] 2021-11-23 16:33
Right and if we were to introduce a breaking change to remove/disable this plugin it would have to be in 2.0.0.

**Comment by nicholasio** [comment] 2021-12-01 18:47
@joesnellpdx and I discussed and we'll update 10up-toolkit to so that postcss editor style plugin is disabled by default and wp-scaffold will be updated to use `add_editor_stype`

**Comment by nicholasio** [comment] 2022-02-08 14:25
Closing this since we're now officially recommending using `add_editor_style` instead of postcss

https://github.com/10up/wp-scaffold/pull/69

**Closed as completed by nicholasio** 2022-02-08 14:25 UTC
